### ISSUE TITLE
Can't build locally on Windows WSL

### ISSUE THREAD

**Issue by etremel** [csci-1301/csci-1301.github.io#24]
Earlier this week I was able to build the lecture notes locally on my computer, which is a Windows machine with Pandoc/LaTeX installed in WSL, by running `make book` in my Ubuntu terminal. However, today when I tried to rebuild them (to preview my changes locally), it failed with the following error:

```

kpathsea: Running mktextfm Symbola
/usr/share/texlive/texmf-dist/web2c/mktexnam: Could not map source abbreviation S for Symbola.
/usr/share/texlive/texmf-dist/web2c/mktexnam: Need to update /usr/share/texlive/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input Symbola
This is METAFONT, Version 2.7182818 (TeX Live 2019/Debian) (preloaded base=mf)


kpathsea: Running mktexmf Symbola
! I can't find file `Symbola'.
<*> ...=ljfour; mag:=1; nonstopmode; input Symbola

Please type another input file name
! Emergency stop.
<*> ...=ljfour; mag:=1; nonstopmode; input Symbola

Transcript written on mfput.log.
grep: Symbola.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input Symbola' failed to make Symbola.tfm.
kpathsea: Appending font creation commands to missfont.log.
```

It seems like the LaTeX toolchain can't find a font named Symbola, but I have both texlive-fonts-recommended and texlive-fonts-extra installed, so I don't know how I could be missing this font. I have installed all the dependencies listed in [the user guide](https://csci-1301.github.io/user_guide.html#installing-required-dependencies-1), and double-checked with the [linked build script](https://github.com/csci-1301/csci-1301.github.io/blob/f80f8f6b0dab450441e43ad09db2cda0b1fba6e1/.github/workflows/build.yaml#L27-L30), but I've installed everything listed there as well.

What package am I missing that would allow me to build the lecture notes locally?

**Comment by aubertc** [comment]
It seems that you are linking to an old version of the build script. The [updated one](https://github.com/csci-1301/csci-1301.github.io/blob/main/.github/workflows/pull.yaml) includes mention of the `fonts-symbola` package which is now needed to produce the emoticons in the pdf.

**Comment by aubertc** [comment]
The user guide was providing the faulty link, it is fixed with https://github.com/csci-1301/csci-1301.github.io/commit/636b0c163308ddd4350004e83627d228c9aa47cf

Let me know if you need more instructions on how to install this font, normally a simple `apt-get install fonts-symbola` should do.

**Comment by etremel** [comment]
Yes, that package was all I needed, and I was following the link from the user guide, which is why I didn't realize the build script had been updated.  Thanks for fixing it.
