### ISSUE TITLE
Mirroring of the website

### ISSUE THREAD

**Issue by aubertc** [csci-1301/csci-1301.github.io#26]
This issue briefly discuss the mirroring of our resource across the internet.
<https://csci-1301.github.io/> is nice, but not "AU-approved", as far as I know, so it is better to have alternative hosting(s), so that we can always access the resource no matter the network or github's policies.

Our three goals were:

> :heavy_check_mark: Package releases will be available under repository releases
> :alarm_clock: AU server and box will host a mirror, which maybe need to be uploaded manually
> :alarm_clock: Packages are periodically archived on Galileo

AU server (spots) and box are partially done, cf. below.
The annoying bit is that it currently is linked to _my accounts_, on _my computer_: if I am not behind my computer at Augusta University (or, rather, if my computer is not turned on and correctly connected), the backup does not take place.

# Box

[Using this guide](https://developer.box.com/guides/tooling/cli/quick-start/create-jwt-app/), I was able to install and configure the command-line interface, but, alas…

```
$ box users:get
Unexpected API Response [400 Bad Request] unauthorized_client - This app is not authorized by the enterprise admin
```

So, I felt back on the [ftp interface](https://augustauniversity.app.box.com/services/box_ftp_server) (cf. also [this doc.](https://support.box.com/hc/en-us/articles/360043697414-Using-Box-with-FTP-or-FTPS)) which seems to be working ok (cf. <https://augustauniversity.app.box.com/folder/138426760013>).

I believe anyone with the link <https://augustauniversity.box.com/s/omis1adqth97bouvwxfwmlhwyiv6gwo1> can access and download the resource. Can you please "@all" (no way of tagging every contributor?) confirm?

# Spots

I am mirroring on my web page, at <https://spots.augusta.edu/caubert/teaching/csci-1301/>. @richdefrancisco , if I remember correctly, you were investigating the possibility of obtaining a <https://spots.augusta.edu/csci-1301/> account, how did that go?

# Galileo

Per <https://oer.galileo.usg.edu/faq.html#faq-3>:

> Can faculty and staff submit materials to the repository directly?
>
>    At the moment, GALILEO Open Learning Materials uploads are administrator-only. If you would like to add your materials to the collection, please email Jeff Gallant at jeff.gallant@usg.edu.

We will have to create a "sum.pdf" containing the labs and lecture notes, possibly along additional material, and send it to them directly, by hand, I'm afraid. I will check on that.

**Comment by richdefrancisco** [comment]
With regard to spots, I put in the request but unfortunately AU Service-Now was unable to provide a course-specific spots directory tied to multiple users.  Perhaps instead we could see if a course server could be set up within SCCS, especially if this project becomes a template for other shared courses.  I am not sure what that would entail, but it seems like it should be feasible.

**Comment by aubertc** [comment]
Ok thanks.
Having a School's server is probably a whole different project.

**Comment by aubertc** [comment]
We are now archived on Galilleo, check out
https://alg.manifoldapp.org/read/csci-1301-book/
and
https://oer.galileo.usg.edu/compsci-textbooks/15/

The updates are not automatic, but I think we can close this issue as resolved.
