### ISSUE TITLE
Reviewing list of topics

### ISSUE THREAD

**Issue by nkrusch** [csci-1301/csci-1301.github.io#47]
Going over the list to make sure I have covered everything. Some comments:

- [The `String.Format` method](https://github.com/csci-1301/csci-1301.github.io/blob/main/docs/topics_list.md#displaying-strings-on-the-screen)

   This is listed as required. Should it be? There was a time before interpolation syntax was introduced, and this used to be the way. Either interpolation or String.Format can achieve the same thing. Covering both may be confusing?

- [Characters](https://github.com/csci-1301/csci-1301.github.io/blob/main/docs/topics_list.md#characters)

   There is no `Contains`, `StartsWith`, `EndsWith` for characters. 

- [enum](https://github.com/csci-1301/csci-1301.github.io/blob/main/docs/topics_list.md#enumerated-datatype)

   Is marked required? I was not planning on teaching it.

- should add "conditional operator ❓" somewhere

   it is already mentioned in lecture and lab notes.

**Comment by aubertc** [comment]
> The String.Format method

There is something you cannot do with interpolation, which is e.g. "display this string using XX characters, padding it to the right with space if needed". I used to discuss it briefly in a project and the related lab (cf. https://github.com/csci-1301/initial-matrix/blob/e2c5837b690145801a2b19d632dd0de0bab3ea99/resources/internal/clement/website/weekly/14/project/index.md#hint-2---displaying ).
It should be marked as optional, but is worth discussing if times allow, I believe.

I don't think it should be _required_, that being said.

> Characters

Yes, that is probably a typo. We could have `IsUpper`, ` ToLower`, `ToUpper`, for instance, though.

> should add "conditional operator question" somewhere

Then it's done :-)

**Comment by richdefrancisco** [comment]
You actually don't need to use String.Format to display with padding if you are using interpolation.
Console.WriteLine($"Thing I want to print {value,10}");
will work in much the same way as String.Format (right-aligned in a field of 10 char length).
See: [https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated)

**Comment by nkrusch** [comment]
What way of formatting is used in 1302? I feel we should use the same in 1301.
