### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by nkrusch** [csci-1301/csci-1301.github.io#48]
There is currently a build warning with following message:

```
Could not fetch resource img/activity_diag_vote_if_else.pdf: replacing image with description
```

Tagging @aubertc

**Comment by aubertc** [comment]
Sorry, this should be fixed with https://github.com/csci-1301/csci-1301.github.io/commit/b099f978a02049bafff5bafc4ea5a3e15b3288b0.
