### ISSUE TITLE
Redundant foreach sections

### ISSUE THREAD

**Issue by etremel** [csci-1301/csci-1301.github.io#50]
We currently have two different sections of our lecture notes that discuss `foreach` loops, `break`, and `continue`. The first is here, in the section "for loops with arrays": https://csci-1301.github.io/book.html#for-loops-with-arrays-1. The second is here, as a standalone section: https://csci-1301.github.io/book.html#foreach-loop.

I'm guessing there was a miscommunication in planning the lecture organization, but which structure was intended? How should we combine these?

**Comment by aubertc** [comment]
You are absolutely correct that those two should be combined. I don't have the structure fresh in my head enough to decide how to re-organize those, but I agree there should be a merging.

**Comment by aubertc** [comment]
The `foreach` loops are now only discussed in https://csci-1301.github.io/book.html#the-foreach-loop-1
