### ISSUE TITLE
Labs table

### ISSUE THREAD

**Issue by nkrusch** [csci-1301/csci-1301.github.io#58]
**Reference**

https://csci-1301.github.io/labs/

**Describe the issue**

This table is currently being auto-generated since the labs were changing a lot, and new ones we being added. The labs are now in a more stable state, so this table can be created manually and with better formatting.

**Suggested solution**

Replace the auto-generating section with manually editable markdown table, perhaps similar to the [slides table](https://github.com/csci-1301/csci-1301.github.io/blob/main/docs/slides.md)

**Comment by aubertc** [comment]
This was largely taken care of with https://github.com/csci-1301/csci-1301.github.io/commit/39e7a851b5d5b1727fc288b0fa2fea36ee5d4997
