### ISSUE TITLE
Grade calculator

### ISSUE THREAD

**Issue by aubertc** [csci-1301/csci-1301.github.io#80]
There is an issue with [the grade calculator solution](https://github.com/csci-1301/csci-1301.github.io/blob/main/labs/GradeCalculator/src/Grade_Calculator_with_Arrays/Grade_Calculator_with_Arrays/Program.cs), @jweeks2023 

Cf. the example below:

```
For all the questions below, enter, as an integer, 
        - your grade, or
        - "0" if you missed the evaluation, or
        - "-1" if that evaluation did not happened yet.
What was your grade for quiz 1 (out of 20)?
20
What was your grade for quiz 2 (out of 20)?
-1
Your average for the quiz is 100.00 %.
What was your grade for project 1 (out of 20)? 
20
What was your grade for project 2 (out of 20)? 
-1
Your average for the project is 100.00 %.
What was your grade for in-class test 1 (out of 100)? 
100
What was your grade for in-class test 2 (out of 100)? 
-1
Your average for the tests is 100.00 %.
What was your grade for the final (out of 200)?
-1
Your average so far is 37.50 %.
```

The average so far is _not_  37.50 %, it should be 100%.

Please, reword the instructions if they are not clear, or fix your solution.

**Comment by aubertc** [comment]
Thanks for closing it, @jweeks2023 . When closing issues, don't hesitate to link to the actual commit that solved it, like so: https://github.com/csci-1301/csci-1301.github.io/commit/4d79a8eb258c81ec44bc7d01d729f4f09d015ac4

**Comment by jweeks2023** [comment]
Understood, thanks for letting me know.
